// Isolated browser harness. All rows live in a single PostgreSQL temporary schema.
// Explicit opt-in, localhost only, fake accounts and in-memory photo storage.
if (process.env.RUN_AUDIT_BROWSER_TESTS !== '1') throw new Error('Set RUN_AUDIT_BROWSER_TESTS=1 for this test fixture');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
const express = require('express');
const cors = require('cors');
const fs = require('fs');
const jwt = require('jsonwebtoken');
const { Client } = require('pg');
process.env.JWT_SECRET = 'isolated-audit-browser-fixture';
const png = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==';
const storage = require('../utils/s3Upload');
storage.getSignedReadUrl = () => png;
storage.uploadBufferToS3 = async ({ key }) => ({ key, url: png });
const audit = require('../modules/auth/v1/controllers/auditController');
const qg = require('../modules/auth/v1/controllers/qgController');
const auth = require('../middlewares/auth');
const account = require('../middlewares/requireAdminAccount');
const roles = require('../middlewares/requireAnyRole');
const { databaseTypes } = require('../utils/malaysiaTime');
(async () => {
  const db = new Client({ connectionString: process.env.DATABASE_URL, types: databaseTypes, options: '-c timezone=UTC' });
  await db.connect();
  await db.query(`SET search_path TO pg_temp;
    CREATE TEMP TABLE admins(id bigint PRIMARY KEY, username text, is_active boolean);
    CREATE TEMP TABLE masterlist(no bigint PRIMARY KEY, fitment_id text, chassis text, model_description text, cafi_date date, cancel_time timestamp, seq int, model_code text, colour text);
    CREATE TEMP TABLE checkin(no bigint PRIMARY KEY, masterlist_id bigint, type text, status text, checkin_time timestamp, checkout_time timestamp, created_at timestamp, bay_id bigint, remark text);
    CREATE TEMP TABLE bay(no bigint PRIMARY KEY, name text);
    CREATE TEMP TABLE staff(no bigint PRIMARY KEY, name text, staff_id text);
    CREATE TEMP TABLE checkin_staff(checkin_id bigint, staff_id bigint);
    CREATE TEMP TABLE qg_job(id bigserial PRIMARY KEY, masterlist_id bigint, task_type text, status text, latest_inspection_id bigint, source_checkin_id bigint, available_at timestamp, updated_at timestamp, UNIQUE(masterlist_id,task_type));
    CREATE TEMP TABLE qg_inspection(id bigint PRIMARY KEY, qg_job_id bigint, result text, inspected_at timestamp, inspected_by bigint, attempt_no int, general_remark text, voided_at timestamp);
    CREATE TEMP TABLE qg_inspection_defect(id bigint PRIMARY KEY, inspection_id bigint, issue_id bigint, issue_name text, description_id bigint, area_id bigint, description_name text, area_name text, sequence_no int, remark text, parts_type text, part_name text, approved_at timestamptz, approved_by bigint);
    CREATE TEMP TABLE qg_defect_photo(id bigint, defect_id bigint, storage_key text, file_name text);
    CREATE TEMP TABLE qg_defect_issue(id bigint PRIMARY KEY, name text, code text, task_type text, sort_order int, is_active boolean);
    CREATE TEMP TABLE qg_defect_option(id bigint PRIMARY KEY, name text, category text, sort_order int, is_active boolean);
    CREATE TEMP TABLE task_item(no bigint PRIMARY KEY, masterlist_id bigint, type text, short_name text);
    INSERT INTO admins VALUES (1,'Supervisor Test',true),(2,'QG Test',true),(3,'Admin Test',true);
    INSERT INTO masterlist VALUES (1,'V-AUDIT-DEMO','DEMO-CHASSIS','Demo Vehicle',(NOW() AT TIME ZONE 'Asia/Kuala_Lumpur')::date,NULL,1,'DEMO','White');
    INSERT INTO bay VALUES (1,'Demo bay');
    INSERT INTO checkin VALUES (1,1,'FITMENT','Check-Out',NOW() AT TIME ZONE 'Asia/Kuala_Lumpur',NOW() AT TIME ZONE 'Asia/Kuala_Lumpur',NOW() AT TIME ZONE 'UTC',1,'Test installation');
    INSERT INTO qg_job VALUES (1,1,'FITMENT','APPROVED',10,1,NOW() AT TIME ZONE 'Asia/Kuala_Lumpur',NOW());
    INSERT INTO qg_inspection VALUES (10,1,'APPROVED',NOW() AT TIME ZONE 'UTC',2,1,NULL,NULL);
    INSERT INTO qg_defect_issue VALUES (1,'Installation','INSTALLATION','ALL',1,true);
    INSERT INTO qg_defect_option VALUES (2,'Loose fitting','description',1,true),(3,'Front','area',1,true),(4,'OE part','oe',1,true);
    INSERT INTO task_item VALUES (5,1,'FITMENT','Dash camera');
  `);
  await db.query(fs.readFileSync(path.join(__dirname, '../postgreSQL/audit_check.sql'), 'utf8'));
  const app = express(); app.use(cors()); app.use(express.json());
  app.set('pool', { query: (...args) => db.query(...args), connect: async () => ({ query: (...args) => db.query(...args), release() {} }) });
  app.use((req,res,next) => { res.error = (_name, message, status) => res.status(status).json({ success:false, message }); next(); });
  app.post('/auth/adminLogin', (req,res) => {
    const role = req.body.email === 'qg@test.invalid' ? 'qg' : req.body.email === 'admin@test.invalid' ? 'admin' : 'supervisor';
    const id = role === 'qg' ? 2 : role === 'admin' ? 3 : 1;
    res.json({ data: { accessToken: jwt.sign({ id, role, type: 'admin' },process.env.JWT_SECRET,{ expiresIn: '1h' }), admin: { id, role, username: `${role} Test` } } });
  });
  app.get('/auth/audit/capabilities',auth,account,audit.capabilities);
  app.get('/auth/audit/jobs',auth,account,audit.jobs);
  app.get('/auth/audit/jobs/:jobId',auth,account,audit.job);
  app.get('/auth/audit/inspections',auth,account,audit.list);
  app.get('/auth/audit/inspections/:auditId',auth,account,audit.detail);
  app.post('/auth/audit/jobs/:jobId/photos',auth,account,roles('supervisor','superadmin'),express.raw({type:'image/png',limit:'10mb'}),audit.photo);
  app.post('/auth/audit/jobs/:jobId/inspections',auth,account,roles('supervisor','superadmin'),audit.submit);
  app.post('/auth/audit/inspections/:auditId/cancel',auth,account,roles('supervisor','superadmin'),audit.cancel);
  app.get('/auth/qg/dashboard',auth,account,qg.dashboard);
  app.get('/auth/qg/inspections',auth,account,qg.inspections);
  app.get('/auth/qg/inspections/:inspectionId',auth,account,qg.inspectionDetail);
  app.get('/auth/qg/defect-options',auth,account,qg.options);
  app.get('/auth/qg/jobs/:jobId',auth,account,qg.detail);
  app.use((error,req,res,next) => { console.error(error.message); res.status(error.status || 500).json({success:false,message:error.message}); });
  const server=app.listen(5188,'127.0.0.1',()=>console.log('Audit fixture ready on 127.0.0.1:5188; temporary data only'));
  const stop=()=>server.close(()=>db.end().then(()=>process.exit()));
  process.on('SIGTERM',stop);process.on('SIGINT',stop);
})().catch(error=>{console.error(error.message);process.exitCode=1});
